import { SymptomInput, AssessmentResult, EmergencyProtocol } from '../types/health';
import { generateMockAssessment } from '../data/symptoms';
import { EMERGENCY_PROTOCOLS } from '../data/emergencies';

const NVIDIA_API_KEY =
  (import.meta.env && import.meta.env.VITE_NVIDIA_API_KEY) ||
  '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';

const NVIDIA_MODEL =
  (import.meta.env && import.meta.env.VITE_NVIDIA_MODEL) ||
  'meta/llama-3.2-11b-vision-instruct';

const NVIDIA_ENDPOINT =
  (import.meta.env && import.meta.env.VITE_NVIDIA_ENDPOINT) ||
  'https://integrate.api.nvidia.com/v1/chat/completions';

export class AIService {
  /**
   * Evaluates symptoms using the NVIDIA NIM AI Agent.
   * - Strictly classifies critical vs non-critical diseases.
   * - Generates tailored, evidence-based home remedies for non-critical conditions.
   * - Falls back to local clinical rule engine if network/API is unavailable.
   */
  public static async analyzeSymptoms(input: SymptomInput, fallbackDelayMs = 1500): Promise<AssessmentResult> {
    if (NVIDIA_API_KEY && typeof fetch !== 'undefined') {
      try {
        const liveResult = await this.callNvidiaAgent(input);
        if (liveResult) {
          return liveResult;
        }
      } catch (err) {
        console.warn('NVIDIA AI API call failed or timed out, using local clinical fallback:', err);
      }
    }

    // Fallback local clinical inference
    return new Promise((resolve) => {
      setTimeout(() => {
        const result = generateMockAssessment(input);
        resolve(result);
      }, fallbackDelayMs);
    });
  }

  /**
   * Invokes NVIDIA NIM Chat Completions API with a clinical triage prompt
   */
  private static async callNvidiaAgent(input: SymptomInput): Promise<AssessmentResult | null> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 12000);

    const systemPrompt = `You are JeevanSetu's Clinical Triage & Health Guidance AI Agent, specialized in Indian rural community healthcare.
Analyze the patient's symptoms, duration, severity, and text description.

CRITICAL TRIAGE RULE:
- Set riskLevel to "CRITICAL" ONLY when a truly life-threatening emergency disease is present:
  e.g., Acute myocardial infarction (heart attack), severe stroke / hemiplegia, venomous snake / scorpion bite, severe respiratory failure / asphyxia / cyanosis, massive arterial bleeding / trauma hemorrhage, severe acute poisoning / chemical ingestion, status epilepticus, or acute obstetric hemorrhage.
- For ANY non-life-threatening or routine conditions (e.g., common cold, viral seasonal fever, bronchitis, migraine / tension headache, dyspepsia / acidity / GERD, diarrhea / mild food poisoning, minor sprains, skin allergies, mild heat fatigue):
  Set riskLevel to "LOW" (for mild, self-limiting discomfort) or "MODERATE" (for illnesses needing a local PHC doctor check within 24-48 hours). NEVER set CRITICAL for simple cold, mild fever, or non-emergency symptoms.

FOR NON-CRITICAL CONDITIONS (LOW & MODERATE):
- You MUST provide 3 to 5 safe, practical, accessible HOME REMEDIES specifically suited for that illness (e.g. herbal infusions like tulsi/ginger, steam inhalation, warm salt water gargle, oral rehydration solutions [ORS] / buttermilk, bland diet like khichdi/bananas, cold compresses, resting posture).
- Provide immediate steps, dietary guidelines, and clear warning signs for when to see a doctor.

FOR CRITICAL CONDITIONS:
- homeRemedies MUST state: "No home remedy is safe or sufficient. Urgent hospital care via 108 ambulance is necessary immediately."
- Provide immediate life-preserving first aid steps.

Output MUST be ONLY a valid JSON object matching this schema without markdown fences:
{
  "riskLevel": "CRITICAL" | "MODERATE" | "LOW",
  "headline": "string",
  "subheadline": "string with emoji",
  "summary": "string (2-3 clear sentences)",
  "warningSigns": ["string", "string"],
  "immediateSteps": ["string", "string"],
  "whatToDo": ["string", "string"],
  "whatToAvoid": ["string", "string"],
  "homeRemedies": ["string", "string", "string"],
  "possibleConditions": [
    {
      "name": "string",
      "likelihood": "Likely" | "Possible" | "Requires Investigation",
      "description": "string",
      "relevance": "string"
    }
  ],
  "timeframe": "string",
  "suggestedCareType": "emergency_hospital" | "clinic_visit" | "home_support",
  "disclaimer": "This assessment is generated by JeevanSetu AI for educational guidance and triage. It is not a definitive diagnosis."
}`;

    const symptomsList = input.symptoms && input.symptoms.length > 0 ? input.symptoms.join(', ') : 'None selected';
    const userPrompt = `Patient Reported Data:
- Symptoms: ${symptomsList}
- Duration: ${input.duration || 'Not specified'}
- Severity: ${input.severity || 'mild'}
- Patient Description: "${input.description || ''}"
- Associated Signs: ${input.associatedSigns ? input.associatedSigns.join(', ') : 'None'}

Provide triage classification and detailed home remedies in the exact JSON format.`;

    try {
      const response = await fetch(NVIDIA_ENDPOINT, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${NVIDIA_API_KEY}`
        },
        body: JSON.stringify({
          model: NVIDIA_MODEL,
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt }
          ],
          temperature: 0.15,
          max_tokens: 1200
        }),
        signal: controller.signal
      });

      clearTimeout(timeout);

      if (!response.ok) {
        throw new Error(`NVIDIA API HTTP ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();
      const content = data.choices && data.choices[0] && data.choices[0].message ? data.choices[0].message.content : '';

      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        throw new Error('Could not parse JSON from AI response');
      }

      const parsed = JSON.parse(jsonMatch[0]);

      // Normalize fields
      const riskLevel =
        parsed.riskLevel === 'CRITICAL' ? 'CRITICAL' : parsed.riskLevel === 'MODERATE' ? 'MODERATE' : 'LOW';

      const result: AssessmentResult = {
        id: `triage-ai-${Date.now()}`,
        timestamp: new Date().toLocaleDateString('en-IN', {
          day: 'numeric',
          month: 'short',
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        }),
        riskLevel,
        headline: parsed.headline || (riskLevel === 'CRITICAL' ? 'CRITICAL MEDICAL ATTENTION REQUIRED' : 'CLINICAL GUIDANCE'),
        subheadline: parsed.subheadline || (riskLevel === 'CRITICAL' ? '🚨 POSSIBLE EMERGENCY DETECTED' : 'SAFE SUPPORTIVE ADVICE'),
        summary: parsed.summary || 'Assessment evaluated based on your reported symptoms.',
        warningSigns: Array.isArray(parsed.warningSigns) ? parsed.warningSigns : ['Difficulty breathing', 'High persistent fever'],
        immediateSteps: Array.isArray(parsed.immediateSteps) ? parsed.immediateSteps : ['Rest in a well-ventilated area'],
        whatToDo: Array.isArray(parsed.whatToDo) ? parsed.whatToDo : ['Hydrate with clean boiled water'],
        whatToAvoid: Array.isArray(parsed.whatToAvoid) ? parsed.whatToAvoid : ['Do not take unprescribed strong medications'],
        homeRemedies: Array.isArray(parsed.homeRemedies) ? parsed.homeRemedies : [],
        possibleConditions: Array.isArray(parsed.possibleConditions) && parsed.possibleConditions.length > 0
          ? parsed.possibleConditions
          : [{ name: 'Clinical Evaluation', likelihood: 'Possible', description: 'Requires in-person review', relevance: 'Based on reported symptoms' }],
        timeframe: parsed.timeframe || (riskLevel === 'CRITICAL' ? 'IMMEDIATELY (Within 30–60 minutes)' : 'Within 24–48 Hours'),
        suggestedCareType: parsed.suggestedCareType || (riskLevel === 'CRITICAL' ? 'emergency_hospital' : 'home_support'),
        disclaimer: parsed.disclaimer || 'This assessment is for supportive guidance and does not formulate a medical diagnosis.'
      };

      return result;
    } catch (e) {
      clearTimeout(timeout);
      throw e;
    }
  }

  /**
   * Fast emergency protocol lookup
   */
  public static getEmergencyProtocol(slugOrId: string): EmergencyProtocol | undefined {
    return EMERGENCY_PROTOCOLS.find(
      (p) => p.slug.toLowerCase() === slugOrId.toLowerCase() || p.id.toLowerCase() === slugOrId.toLowerCase()
    );
  }

  /**
   * All protocols list
   */
  public static getAllEmergencyProtocols(): EmergencyProtocol[] {
    return EMERGENCY_PROTOCOLS;
  }
}
